---
version: '3.1'
services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    hostname: kafka
    links:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka:9092
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 30000


  schema-registry:
    image: confluentinc/cp-schema-registry
    hostname: schema-registry
    links:
      - kafka
    ports: 
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry

    
  scala-crawler-web:
    image: scala-crawler-web:0.1.0-SNAPSHOT
    hostname: scala-crawler-web
    links:
      - kafka
      - schema-registry
    ports:
      - 8181:8181
    environment:
      SCALA_CRAWLER_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SCALA_CRAWLER_SCHEMA_REGISTRY_URL: http://schema-registry:8081

  scala-crawler-crawl:
    image: scala-crawler-crawl:0.1.0-SNAPSHOT
    hostname: scala-crawler-crawl
    links:
      - kafka
      - schema-registry
    ports:
      - 8182:8182
    environment:
      SCALA_CRAWLER_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SCALA_CRAWLER_SCHEMA_REGISTRY_URL: http://schema-registry:8081

  redis:
    image: redis:5.0.5
    hostname: redis
    ports:
      - 6379:6379
    links:
      - scala-crawler-web
      - scala-crawler-crawl
    volumes:
      - ./redis:/redis/data
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      #REDIS_BASEDIR: /bitnami/redis/data
      #REDIS_VOLUME: /bitnami/redis/data
      #REDIS_LOGDIR: /bitnami/redis/data/log













