---
version: '3.1'
services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    hostname: kafka
    links:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka:9092
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 30000


  schema-registry:
    image: confluentinc/cp-schema-registry
    hostname: schema-registry
    links:
      - kafka
    ports: 
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry

    
  scala-crawler:
    image: scala-crawler:0.1.0-SNAPSHOT
    hostname: scala-crawler
    links:
      - kafka
      - schema-registry
    ports:
      - 8181:8181
    environment:
      SCALA_CRAWLER_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SCALA_CRAWLER_SCHEMA_REGISTRY_URL: schema-registry:8081
